### PR TITLE
three-fingers-swipe to screenshot

### PR DESCRIPTION
**Pull request by Kitsunejasutin**
hyaaaa

### CODE REVIEW

**Comment by AdarshGrewal** [comment]
@Kitsunejasutin Nice

**Comment by basamaryan** [comment]
i like squash

**Comment by Twel12** [comment]
No

**Comment by AdarshGrewal** [comment]
@Twel12 Merge when

**Comment by AdarshGrewal** [comment]
@AdarshGrewal Why close

**Comment by AdarshGrewal** [comment]
@AdarshGrewal +1 +2

**Comment by Kitsunejasutin** [comment]
My bad, wrong pr. didn' t realized it's on main repo

**Comment by vansh123456** [comment]
@Kitsunejasutin Myman

**Pull request closed without merging**
