### PR TITLE
bootanimation: Always use normal bootanimation

### PR DESCRIPTION
**Pull request by asriadirahim**
This commit will fix issue like this https://t.me/c/1682814765/685 after restar the system
Status: Build and test on Pixel 2XL

### CODE REVIEW

**Comment by bheatleyyy** [comment]
> This commit will fix issue like this https://t.me/c/1682814765/685 after restar the system Status: Build and test on Pixel 2XL

Sorry the link you shared is inaccessible

**Comment by asriadirahim** [comment]
> > This commit will fix issue like this https://t.me/c/1682814765/685 after restar the system Status: Build and test on Pixel 2XL
> 
> Sorry the link you shared is inaccessible

Ah..sory for my bad, this is the link https://t.me/artesting/2, just too lazy uploading on internet, so i use tele for this :)

**Comment by Fentaniloso** [comment]
asriadirahim:thirteen

**Comment by Fentaniloso** [comment]
#23

**Pull request merged**
